# Generated by Django 5.1.2 on 2024-11-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_lease_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roommate_preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
