# Generated by Django 5.1.2 on 2024-12-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_user_hobbies_user_personal_info_and_more'),
        ('housing', '0010_remove_review_user'),
    ]

    operations = [
    ]
