name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_v2.txt
        pip install coveralls
    - name: Run Tests
      run: |
        coverage run manage.py test housing.test_email_notification
        coverage report
        coverage xml
    - name: Upload Coverage to Coveralls
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.WOLFLEASE_SECRET }}

#    - name: Generate Test Coverage
#      run: |
#        coverage report
#        coverage json
#    - name: Generate HTML Pages for Test COverage
#      run: |
#        coverage html
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v3
#      with:
#        token: "c640c7b0-44f1-4c81-823a-ddfdc89ff703"
#        directory: ./htmlcov/
#        env_vars: OS,PYTHON
#        fail_ci_if_error: true
#        files: ./coverage.json
#        flags: unittests
#        name: codecov-umbrella
#        verbose: true
